/**
 * Generates src/lib/data/shuk-items.ts — 30 market items for אתגר השוק.
 *
 * Run: npx tsx scripts/generate-shuk-items.ts
 */
import { writeFileSync } from "fs";
import { join } from "path";

export interface ShukItemDef {
  name: string;
  nameHe: string;
  price: number;
  emoji: string;
}

const EXPECTED_COUNT = 30;

const RAW: ShukItemDef[] = [
  { name: "Apple", nameHe: "תפוח", price: 3, emoji: "🍎" },
  { name: "Banana", nameHe: "בננה", price: 2, emoji: "🍌" },
  { name: "Orange", nameHe: "תפוז", price: 3, emoji: "🍊" },
  { name: "Bread", nameHe: "לחם", price: 8, emoji: "🍞" },
  { name: "Juice", nameHe: "מיץ", price: 6, emoji: "🧃" },
  { name: "Water", nameHe: "מים", price: 5, emoji: "💧" },
  { name: "Cookie", nameHe: "עוגייה", price: 4, emoji: "🍪" },
  { name: "Chips", nameHe: "חטיף", price: 7, emoji: "🥔" },
  { name: "Tomato", nameHe: "עגבניה", price: 4, emoji: "🍅" },
  { name: "Cucumber", nameHe: "מלפפון", price: 3, emoji: "🥒" },
  { name: "Carrot", nameHe: "גזר", price: 2, emoji: "🥕" },
  { name: "Cheese", nameHe: "גבינה", price: 9, emoji: "🧀" },
  { name: "Egg", nameHe: "ביצה", price: 2, emoji: "🥚" },
  { name: "Milk", nameHe: "חלב", price: 6, emoji: "🥛" },
  { name: "Yogurt", nameHe: "יוגורט", price: 5, emoji: "🥄" },
  { name: "Pizza slice", nameHe: "פרוסת פיצה", price: 10, emoji: "🍕" },
  { name: "Sandwich", nameHe: "כריך", price: 12, emoji: "🥪" },
  { name: "Salad", nameHe: "סלט", price: 8, emoji: "🥗" },
  { name: "Soup", nameHe: "מרק", price: 7, emoji: "🍲" },
  { name: "Chocolate", nameHe: "שוקולד", price: 5, emoji: "🍫" },
  { name: "Ice cream", nameHe: "גלידה", price: 8, emoji: "🍦" },
  { name: "Grapes", nameHe: "ענבים", price: 6, emoji: "🍇" },
  { name: "Strawberry", nameHe: "תות", price: 5, emoji: "🍓" },
  { name: "Lemon", nameHe: "לימון", price: 2, emoji: "🍋" },
  { name: "Potato", nameHe: "תפוח אדמה", price: 3, emoji: "🥔" },
  { name: "Onion", nameHe: "בצל", price: 2, emoji: "🧅" },
  { name: "Honey", nameHe: "דבש", price: 9, emoji: "🍯" },
  { name: "Tea", nameHe: "תה", price: 4, emoji: "🍵" },
  { name: "Coffee", nameHe: "קפה", price: 6, emoji: "☕" },
  { name: "Croissant", nameHe: "קרואסון", price: 7, emoji: "🥐" },
];

function validate(items: ShukItemDef[]): void {
  if (items.length !== EXPECTED_COUNT) {
    throw new Error(`Expected ${EXPECTED_COUNT} items, got ${items.length}`);
  }
  const names = new Set<string>();
  for (const item of items) {
    if (names.has(item.name)) throw new Error(`Duplicate: ${item.name}`);
    names.add(item.name);
    if (item.price < 1 || item.price > 15) throw new Error(`Bad price: ${item.name}`);
  }
}

function main(): void {
  validate(RAW);
  const lines = RAW.map(
    (i) =>
      `  { name: ${JSON.stringify(i.name)}, nameHe: ${JSON.stringify(i.nameHe)}, price: ${i.price}, emoji: ${JSON.stringify(i.emoji)} },`
  );
  const out = `/** Auto-generated by scripts/generate-shuk-items.ts — do not edit manually. */

export interface ShukItem {
  name: string;
  nameHe: string;
  price: number;
  emoji: string;
}

export const SHUK_ITEMS: ShukItem[] = [
${lines.join("\n")}
];
`;
  const outPath = join(process.cwd(), "src/lib/data/shuk-items.ts");
  writeFileSync(outPath, out, "utf8");
  console.log(`Wrote ${RAW.length} shuk items to ${outPath}`);
}

main();
