/** Auto-generated by scripts/generate-english-beginner-sentences.ts — do not edit manually. */

export interface SentenceChallenge {
  words: string[];
  correct: string;
  translation: string;
}

export const ENGLISH_BEGINNER_SENTENCES: SentenceChallenge[] = [
  {
    words: ["I","read","a","book"],
    correct: "I read a book",
    translation: "אני קורא ספר",
  },
  {
    words: ["I","like","apples"],
    correct: "I like apples",
    translation: "אני אוהב תפוחים",
  },
  {
    words: ["I","go","to","school"],
    correct: "I go to school",
    translation: "אני הולך לבית ספר",
  },
  {
    words: ["I","eat","an","apple"],
    correct: "I eat an apple",
    translation: "אני אוכל תפוח",
  },
  {
    words: ["I","drink","water"],
    correct: "I drink water",
    translation: "אני שותה מים",
  },
  {
    words: ["I","play","ball"],
    correct: "I play ball",
    translation: "אני משחק בכדור",
  },
  {
    words: ["I","see","a","cat"],
    correct: "I see a cat",
    translation: "אני רואה חתול",
  },
  {
    words: ["I","have","a","dog"],
    correct: "I have a dog",
    translation: "יש לי כלב",
  },
  {
    words: ["I","love","my","mom"],
    correct: "I love my mom",
    translation: "אני אוהב את אמא",
  },
  {
    words: ["I","write","a","letter"],
    correct: "I write a letter",
    translation: "אני כותב מכתב",
  },
  {
    words: ["I","run","fast"],
    correct: "I run fast",
    translation: "אני רץ מהר",
  },
  {
    words: ["I","swim","well"],
    correct: "I swim well",
    translation: "אני שוחה טוב",
  },
  {
    words: ["I","sing","a","song"],
    correct: "I sing a song",
    translation: "אני שר שיר",
  },
  {
    words: ["I","draw","a","picture"],
    correct: "I draw a picture",
    translation: "אני מצייר תמונה",
  },
  {
    words: ["I","wash","my","hands"],
    correct: "I wash my hands",
    translation: "אני שוטף את הידיים",
  },
  {
    words: ["I","open","the","door"],
    correct: "I open the door",
    translation: "אני פותח את הדלת",
  },
  {
    words: ["I","close","the","window"],
    correct: "I close the window",
    translation: "אני סוגר את החלון",
  },
  {
    words: ["I","sit","on","a","chair"],
    correct: "I sit on a chair",
    translation: "אני יושב על כיסא",
  },
  {
    words: ["I","sleep","in","bed"],
    correct: "I sleep in bed",
    translation: "אני ישן במיטה",
  },
  {
    words: ["I","watch","TV"],
    correct: "I watch TV",
    translation: "אני רואה טלוויזיה",
  },
  {
    words: ["She","is","happy"],
    correct: "She is happy",
    translation: "היא שמחה",
  },
  {
    words: ["He","is","tall"],
    correct: "He is tall",
    translation: "הוא גבוה",
  },
  {
    words: ["She","is","kind"],
    correct: "She is kind",
    translation: "היא נחמדה",
  },
  {
    words: ["He","is","strong"],
    correct: "He is strong",
    translation: "הוא חזק",
  },
  {
    words: ["She","likes","music"],
    correct: "She likes music",
    translation: "היא אוהבת מוזיקה",
  },
  {
    words: ["He","plays","football"],
    correct: "He plays football",
    translation: "הוא משחק כדורגל",
  },
  {
    words: ["She","reads","books"],
    correct: "She reads books",
    translation: "היא קוראת ספרים",
  },
  {
    words: ["He","eats","lunch"],
    correct: "He eats lunch",
    translation: "הוא אוכל צהריים",
  },
  {
    words: ["She","has","a","cat"],
    correct: "She has a cat",
    translation: "יש לה חתול",
  },
  {
    words: ["He","goes","home"],
    correct: "He goes home",
    translation: "הוא הולך הביתה",
  },
  {
    words: ["She","runs","fast"],
    correct: "She runs fast",
    translation: "היא רצה מהר",
  },
  {
    words: ["He","helps","me"],
    correct: "He helps me",
    translation: "הוא עוזר לי",
  },
  {
    words: ["She","sings","well"],
    correct: "She sings well",
    translation: "היא שרה יפה",
  },
  {
    words: ["He","writes","stories"],
    correct: "He writes stories",
    translation: "הוא כותב סיפורים",
  },
  {
    words: ["She","loves","animals"],
    correct: "She loves animals",
    translation: "היא אוהבת חיות",
  },
  {
    words: ["The","dog","is","big"],
    correct: "The dog is big",
    translation: "הכלב גדול",
  },
  {
    words: ["The","cat","is","small"],
    correct: "The cat is small",
    translation: "החתול קטן",
  },
  {
    words: ["The","sun","is","hot"],
    correct: "The sun is hot",
    translation: "השמש חמה",
  },
  {
    words: ["The","sky","is","blue"],
    correct: "The sky is blue",
    translation: "השמיים כחולים",
  },
  {
    words: ["The","flower","is","red"],
    correct: "The flower is red",
    translation: "הפרח אדום",
  },
  {
    words: ["The","book","is","new"],
    correct: "The book is new",
    translation: "הספר חדש",
  },
  {
    words: ["The","car","is","fast"],
    correct: "The car is fast",
    translation: "המכונית מהירה",
  },
  {
    words: ["The","baby","is","cute"],
    correct: "The baby is cute",
    translation: "התינוק חמוד",
  },
  {
    words: ["The","tree","is","tall"],
    correct: "The tree is tall",
    translation: "העץ גבוה",
  },
  {
    words: ["The","house","is","big"],
    correct: "The house is big",
    translation: "הבית גדול",
  },
  {
    words: ["The","fish","is","wet"],
    correct: "The fish is wet",
    translation: "הדג רטוב",
  },
  {
    words: ["The","bird","is","free"],
    correct: "The bird is free",
    translation: "הציפור חופשיה",
  },
  {
    words: ["The","cake","is","sweet"],
    correct: "The cake is sweet",
    translation: "העוגה מתוקה",
  },
  {
    words: ["The","milk","is","cold"],
    correct: "The milk is cold",
    translation: "החלב קר",
  },
  {
    words: ["The","park","is","fun"],
    correct: "The park is fun",
    translation: "הפארק כיפי",
  },
  {
    words: ["The","dog","is","brown"],
    correct: "The dog is brown",
    translation: "הכלב חום",
  },
  {
    words: ["The","apple","is","green"],
    correct: "The apple is green",
    translation: "התפוח ירוק",
  },
  {
    words: ["The","sea","is","deep"],
    correct: "The sea is deep",
    translation: "הים עמוק",
  },
  {
    words: ["The","moon","is","bright"],
    correct: "The moon is bright",
    translation: "הירח בהיר",
  },
  {
    words: ["The","school","is","near"],
    correct: "The school is near",
    translation: "בית הספר קרוב",
  },
  {
    words: ["We","play","together"],
    correct: "We play together",
    translation: "אנחנו משחקים ביחד",
  },
  {
    words: ["We","go","to","park"],
    correct: "We go to park",
    translation: "אנחנו הולכים לפארק",
  },
  {
    words: ["We","like","pizza"],
    correct: "We like pizza",
    translation: "אנחנו אוהבים פיצה",
  },
  {
    words: ["We","read","stories"],
    correct: "We read stories",
    translation: "אנחנו קוראים סיפורים",
  },
  {
    words: ["We","eat","lunch"],
    correct: "We eat lunch",
    translation: "אנחנו אוכלים צהריים",
  },
  {
    words: ["We","sing","songs"],
    correct: "We sing songs",
    translation: "אנחנו שרים שירים",
  },
  {
    words: ["We","help","friends"],
    correct: "We help friends",
    translation: "אנחנו עוזרים לחברים",
  },
  {
    words: ["We","run","fast"],
    correct: "We run fast",
    translation: "אנחנו רצים מהר",
  },
  {
    words: ["We","swim","today"],
    correct: "We swim today",
    translation: "אנחנו שוחים היום",
  },
  {
    words: ["They","are","friends"],
    correct: "They are friends",
    translation: "הם חברים",
  },
  {
    words: ["They","play","ball"],
    correct: "They play ball",
    translation: "הם משחקים בכדור",
  },
  {
    words: ["They","go","to","school"],
    correct: "They go to school",
    translation: "הם הולכים לבית ספר",
  },
  {
    words: ["They","like","cats"],
    correct: "They like cats",
    translation: "הם אוהבים חתולים",
  },
  {
    words: ["They","eat","fruit"],
    correct: "They eat fruit",
    translation: "הם אוכלים פירות",
  },
  {
    words: ["They","read","books"],
    correct: "They read books",
    translation: "הם קוראים ספרים",
  },
  {
    words: ["You","are","nice"],
    correct: "You are nice",
    translation: "את/ה נחמד/ה",
  },
  {
    words: ["You","can","run"],
    correct: "You can run",
    translation: "את/ה יכול/ה לרוץ",
  },
  {
    words: ["You","like","dogs"],
    correct: "You like dogs",
    translation: "את/ה אוהב/ת כלבים",
  },
  {
    words: ["You","have","talent"],
    correct: "You have talent",
    translation: "יש לך כישרון",
  },
  {
    words: ["You","sing","well"],
    correct: "You sing well",
    translation: "את/ה שר/ה יפה",
  },
  {
    words: ["You","read","fast"],
    correct: "You read fast",
    translation: "את/ה קורא/ת מהר",
  },
  {
    words: ["You","play","well"],
    correct: "You play well",
    translation: "את/ה משחק/ת טוב",
  },
  {
    words: ["You","are","smart"],
    correct: "You are smart",
    translation: "את/ה חכם/ה",
  },
  {
    words: ["You","help","me"],
    correct: "You help me",
    translation: "את/ה עוזר/ת לי",
  },
  {
    words: ["You","eat","apples"],
    correct: "You eat apples",
    translation: "את/ה אוכל/ת תפוחים",
  },
  {
    words: ["My","name","is","Dan"],
    correct: "My name is Dan",
    translation: "קוראים לי דן",
  },
  {
    words: ["My","dog","is","big"],
    correct: "My dog is big",
    translation: "הכלב שלי גדול",
  },
  {
    words: ["My","book","is","here"],
    correct: "My book is here",
    translation: "הספר שלי כאן",
  },
  {
    words: ["My","mom","is","kind"],
    correct: "My mom is kind",
    translation: "אמא שלי נחמדה",
  },
  {
    words: ["Your","cat","is","cute"],
    correct: "Your cat is cute",
    translation: "החתול שלך חמוד",
  },
  {
    words: ["Your","house","is","big"],
    correct: "Your house is big",
    translation: "הבית שלך גדול",
  },
  {
    words: ["His","ball","is","red"],
    correct: "His ball is red",
    translation: "הכדור שלו אדום",
  },
  {
    words: ["Her","dress","is","blue"],
    correct: "Her dress is blue",
    translation: "השמלה שלה כחולה",
  },
  {
    words: ["My","friend","is","here"],
    correct: "My friend is here",
    translation: "החבר שלי כאן",
  },
  {
    words: ["My","room","is","clean"],
    correct: "My room is clean",
    translation: "החדר שלי נקי",
  },
  {
    words: ["Your","hat","is","green"],
    correct: "Your hat is green",
    translation: "הכובע שלך ירוק",
  },
  {
    words: ["His","bike","is","new"],
    correct: "His bike is new",
    translation: "האופניים שלו חדשים",
  },
  {
    words: ["Her","bag","is","pink"],
    correct: "Her bag is pink",
    translation: "התיק שלה ורוד",
  },
  {
    words: ["My","dad","is","tall"],
    correct: "My dad is tall",
    translation: "אבא שלי גבוה",
  },
  {
    words: ["Your","shoes","are","nice"],
    correct: "Your shoes are nice",
    translation: "הנעליים שלך יפות",
  },
  {
    words: ["This","is","my","book"],
    correct: "This is my book",
    translation: "זה הספר שלי",
  },
  {
    words: ["That","is","a","cat"],
    correct: "That is a cat",
    translation: "זה חתול",
  },
  {
    words: ["This","is","fun"],
    correct: "This is fun",
    translation: "זה כיף",
  },
  {
    words: ["That","is","big"],
    correct: "That is big",
    translation: "זה גדול",
  },
  {
    words: ["It","is","cold","today"],
    correct: "It is cold today",
    translation: "קר היום",
  },
  {
    words: ["It","is","sunny","today"],
    correct: "It is sunny today",
    translation: "שמשי היום",
  },
  {
    words: ["This","is","my","house"],
    correct: "This is my house",
    translation: "זה הבית שלי",
  },
  {
    words: ["That","is","a","tree"],
    correct: "That is a tree",
    translation: "זה עץ",
  },
  {
    words: ["It","is","very","hot"],
    correct: "It is very hot",
    translation: "חם מאוד",
  },
  {
    words: ["This","is","my","friend"],
    correct: "This is my friend",
    translation: "זה החבר שלי",
  },
  {
    words: ["There","is","a","cat"],
    correct: "There is a cat",
    translation: "יש חתול",
  },
  {
    words: ["There","is","a","dog"],
    correct: "There is a dog",
    translation: "יש כלב",
  },
  {
    words: ["There","are","two","birds"],
    correct: "There are two birds",
    translation: "יש שני ציפורים",
  },
  {
    words: ["There","are","three","books"],
    correct: "There are three books",
    translation: "יש שלושה ספרים",
  },
  {
    words: ["There","is","one","apple"],
    correct: "There is one apple",
    translation: "יש תפוח אחד",
  },
  {
    words: ["There","are","many","flowers"],
    correct: "There are many flowers",
    translation: "יש הרבה פרחים",
  },
  {
    words: ["There","is","a","park"],
    correct: "There is a park",
    translation: "יש פארק",
  },
  {
    words: ["There","are","five","cats"],
    correct: "There are five cats",
    translation: "יש חמישה חתולים",
  },
  {
    words: ["There","are","two","dogs"],
    correct: "There are two dogs",
    translation: "יש שני כלבים",
  },
  {
    words: ["There","is","a","ball"],
    correct: "There is a ball",
    translation: "יש כדור",
  },
  {
    words: ["I","can","swim"],
    correct: "I can swim",
    translation: "אני יכול לשחות",
  },
  {
    words: ["I","can","read"],
    correct: "I can read",
    translation: "אני יכול לקרוא",
  },
  {
    words: ["She","can","sing"],
    correct: "She can sing",
    translation: "היא יכולה לשיר",
  },
  {
    words: ["He","can","run"],
    correct: "He can run",
    translation: "הוא יכול לרוץ",
  },
  {
    words: ["We","can","play"],
    correct: "We can play",
    translation: "אנחנו יכולים לשחק",
  },
  {
    words: ["I","want","water"],
    correct: "I want water",
    translation: "אני רוצה מים",
  },
  {
    words: ["She","wants","cake"],
    correct: "She wants cake",
    translation: "היא רוצה עוגה",
  },
  {
    words: ["He","has","a","bike"],
    correct: "He has a bike",
    translation: "יש לו אופניים",
  },
  {
    words: ["I","have","a","pen"],
    correct: "I have a pen",
    translation: "יש לי עט",
  },
  {
    words: ["They","have","fun"],
    correct: "They have fun",
    translation: "הם נהנים",
  },
  {
    words: ["You","can","jump"],
    correct: "You can jump",
    translation: "את/ה יכול/ה לקפוץ",
  },
  {
    words: ["I","want","an","apple"],
    correct: "I want an apple",
    translation: "אני רוצה תפוח",
  },
  {
    words: ["He","wants","milk"],
    correct: "He wants milk",
    translation: "הוא רוצה חלב",
  },
  {
    words: ["We","have","time"],
    correct: "We have time",
    translation: "יש לנו זמן",
  },
  {
    words: ["She","has","friends"],
    correct: "She has friends",
    translation: "יש לה חברים",
  },
  {
    words: ["I","go","to","bed"],
    correct: "I go to bed",
    translation: "אני הולך לישון",
  },
  {
    words: ["She","goes","to","school"],
    correct: "She goes to school",
    translation: "היא הולכת לבית ספר",
  },
  {
    words: ["He","goes","to","park"],
    correct: "He goes to park",
    translation: "הוא הולך לפארק",
  },
  {
    words: ["We","go","to","beach"],
    correct: "We go to beach",
    translation: "אנחנו הולכים לחוף",
  },
  {
    words: ["They","go","home"],
    correct: "They go home",
    translation: "הם הולכים הביתה",
  },
  {
    words: ["I","am","at","school"],
    correct: "I am at school",
    translation: "אני בבית הספר",
  },
  {
    words: ["She","is","at","home"],
    correct: "She is at home",
    translation: "היא בבית",
  },
  {
    words: ["He","is","in","class"],
    correct: "He is in class",
    translation: "הוא בכיתה",
  },
  {
    words: ["We","are","in","park"],
    correct: "We are in park",
    translation: "אנחנו בפארק",
  },
  {
    words: ["They","are","at","beach"],
    correct: "They are at beach",
    translation: "הם בחוף",
  },
  {
    words: ["Good","morning","everyone"],
    correct: "Good morning everyone",
    translation: "בוקר טוב לכולם",
  },
  {
    words: ["Thank","you","very","much"],
    correct: "Thank you very much",
    translation: "תודה רבה",
  },
  {
    words: ["See","you","tomorrow"],
    correct: "See you tomorrow",
    translation: "נתראה מחר",
  },
  {
    words: ["I","am","hungry","now"],
    correct: "I am hungry now",
    translation: "אני רעב עכשיו",
  },
  {
    words: ["She","is","tired","today"],
    correct: "She is tired today",
    translation: "היא עייפה היום",
  },
  {
    words: ["The","food","is","good"],
    correct: "The food is good",
    translation: "האוכל טוב",
  },
  {
    words: ["I","like","my","teacher"],
    correct: "I like my teacher",
    translation: "אני אוהב את המורה",
  },
  {
    words: ["We","love","our","school"],
    correct: "We love our school",
    translation: "אנחנו אוהבים את בית הספר",
  },
  {
    words: ["The","bus","is","here"],
    correct: "The bus is here",
    translation: "האוטובוס כאן",
  },
  {
    words: ["My","cat","sleeps","now"],
    correct: "My cat sleeps now",
    translation: "החתול שלי ישן עכשיו",
  },
];
