/** Auto-generated by scripts/generate-shuk-items.ts — do not edit manually. */

export interface ShukItem {
  name: string;
  nameHe: string;
  price: number;
  emoji: string;
}

export const SHUK_ITEMS: ShukItem[] = [
  { name: "Apple", nameHe: "תפוח", price: 3, emoji: "🍎" },
  { name: "Banana", nameHe: "בננה", price: 2, emoji: "🍌" },
  { name: "Orange", nameHe: "תפוז", price: 3, emoji: "🍊" },
  { name: "Bread", nameHe: "לחם", price: 8, emoji: "🍞" },
  { name: "Juice", nameHe: "מיץ", price: 6, emoji: "🧃" },
  { name: "Water", nameHe: "מים", price: 5, emoji: "💧" },
  { name: "Cookie", nameHe: "עוגייה", price: 4, emoji: "🍪" },
  { name: "Chips", nameHe: "חטיף", price: 7, emoji: "🥔" },
  { name: "Tomato", nameHe: "עגבניה", price: 4, emoji: "🍅" },
  { name: "Cucumber", nameHe: "מלפפון", price: 3, emoji: "🥒" },
  { name: "Carrot", nameHe: "גזר", price: 2, emoji: "🥕" },
  { name: "Cheese", nameHe: "גבינה", price: 9, emoji: "🧀" },
  { name: "Egg", nameHe: "ביצה", price: 2, emoji: "🥚" },
  { name: "Milk", nameHe: "חלב", price: 6, emoji: "🥛" },
  { name: "Yogurt", nameHe: "יוגורט", price: 5, emoji: "🥄" },
  { name: "Pizza slice", nameHe: "פרוסת פיצה", price: 10, emoji: "🍕" },
  { name: "Sandwich", nameHe: "כריך", price: 12, emoji: "🥪" },
  { name: "Salad", nameHe: "סלט", price: 8, emoji: "🥗" },
  { name: "Soup", nameHe: "מרק", price: 7, emoji: "🍲" },
  { name: "Chocolate", nameHe: "שוקולד", price: 5, emoji: "🍫" },
  { name: "Ice cream", nameHe: "גלידה", price: 8, emoji: "🍦" },
  { name: "Grapes", nameHe: "ענבים", price: 6, emoji: "🍇" },
  { name: "Strawberry", nameHe: "תות", price: 5, emoji: "🍓" },
  { name: "Lemon", nameHe: "לימון", price: 2, emoji: "🍋" },
  { name: "Potato", nameHe: "תפוח אדמה", price: 3, emoji: "🥔" },
  { name: "Onion", nameHe: "בצל", price: 2, emoji: "🧅" },
  { name: "Honey", nameHe: "דבש", price: 9, emoji: "🍯" },
  { name: "Tea", nameHe: "תה", price: 4, emoji: "🍵" },
  { name: "Coffee", nameHe: "קפה", price: 6, emoji: "☕" },
  { name: "Croissant", nameHe: "קרואסון", price: 7, emoji: "🥐" },
];
